on: push
name: Slack Notification Demo
jobs:
  # hello:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Print message
  #       run: echo "Hello GitHub Actions"


  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: checkout
        uses: actions/checkout@v4
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/slack-demo:latest
            ${{ vars.DOCKERHUB_USERNAME }}/slack-demo:${{ github.sha }}

  slackNotification-dockerPush:
    name: Slack Notification
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "Workflow ${{ github.workflow }} has completed. Tagged image: ${{ vars.DOCKERHUB_USERNAME }}/slack-demo:${{ github.sha }} Has been pushed"

  helm-template:
    name: Helm Template
    needs: docker-build-and-push
    
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: Helm Template
      run: helm template "${{ github.event.repository.name }}" ./helm-charts  > "${{ github.event.repository.name }}".yaml

    - name: Print Helm Template
      run: cat "${{ github.event.repository.name }}".yaml

  slackNotification-helmTemplate:
    name: Slack Notification
    needs: helm-template
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "Helm template created successfully"


  pull-argocd:
    needs: helm-template
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v6
      with:
       repository: kfirbros123/argo-gitops
       path: application
    - name: list files
      run: ls -R application



  push-template-to-repo:
    name: Push Template to Repo
    needs: helm-template
    runs-on: ubuntu-latest
    steps:
    - name: read
      run: ls -R .

    # - name: checkout
    #   uses: actions/checkout@v6
    #   run: |
    #       date > generated.txt
    #       # Note: the following account information will not work on GHES
    #       git config user.name "github-actions[bot]"
    #       git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    #       git add .
    #       git commit -m "generated"
    #       git push