on: push
name: CI/CD Workflow with Slack Notification
jobs:

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          files: '**/*.py'

  trivy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/exam-app:${{ github.sha }} .

#/////////////////////////////////////////////////////
#//trivy scan on the built image
#/////////////////////////////////////////////////////

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: '${{ vars.DOCKERHUB_USERNAME }}/exam-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
#/////////////////////////////////////////////////////
#//after trivy save image for next step
#/////////////////////////////////////////////////////
      - name: Save image
        run: |
          docker save ${{ vars.DOCKERHUB_USERNAME }}/exam-app:${{ github.sha }} -o exam-app-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: exam-app-image.tar


  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: [shellcheck, trivy-check]
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load image
        run: |
          docker load -i exam-app-image.tar

      - name: Verify
        run: |
          docker images
      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: checkout
        uses: actions/checkout@v4
      -
        name:  push image to Docker Hub
        run: |
            docker tag ${{ vars.DOCKERHUB_USERNAME }}/exam-app:${{ github.sha }} ${{ vars.DOCKERHUB_USERNAME }}/exam-app:latest
            docker push ${{ vars.DOCKERHUB_USERNAME }}/exam-app:latest
            docker push ${{ vars.DOCKERHUB_USERNAME }}/exam-app:${{ github.sha }}

  helm-template:
    name: Helm Template
    needs: docker-build-and-push
    
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: Helm Template
      run: helm template "${{ github.event.repository.name }}" ./helm-charts  > "${{ github.event.repository.name }}".yaml

    - name: Print Helm Template
      run: cat "${{ github.event.repository.name }}".yaml

    - name: Upload template as artifact
      uses: actions/upload-artifact@v4
      with:
        name: helm-template
        path: "${{ github.event.repository.name }}.yaml"


  pull-commit-push-into-argocd:
    needs: helm-template
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v6
      with:
       repository: kfirbros123/argo-gitops
       ref: application
       path: application
       persist-credentials: false

    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: helm-template  
        path: application/app1/dev/

    - name: list files
      run: ls -Ra application/


     
    - name: commit and push
      run: |
          cd application
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/kfirbros123/argo-gitops.git HEAD:application

  slackNotification-finish-pipeline:
    name: Slack Notification
    needs: pull-commit-push-into-argocd
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: |
          "Workflow ${{ github.workflow }} has completed."
          "Tagged image: ${{ vars.DOCKERHUB_USERNAME }}/exam-app:${{ github.sha }} Has been pushed"
          "Helm template created and pushed to ArgoCD repo successfully."
