on: push
name: Slack Notification Demo
permissions:
  contents: write
jobs:
  # hello:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Print message
  #       run: echo "Hello GitHub Actions"


  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: checkout
        uses: actions/checkout@v4
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/slack-demo:latest
            ${{ vars.DOCKERHUB_USERNAME }}/slack-demo:${{ github.sha }}

  slackNotification-dockerPush:
    name: Slack Notification
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "Workflow ${{ github.workflow }} has completed. Tagged image: ${{ vars.DOCKERHUB_USERNAME }}/slack-demo:${{ github.sha }} Has been pushed"

  helm-template:
    name: Helm Template
    needs: docker-build-and-push
    
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: Helm Template
      run: helm template "${{ github.event.repository.name }}" ./helm-charts  > "${{ github.event.repository.name }}".yaml

    - name: Print Helm Template
      run: cat "${{ github.event.repository.name }}".yaml

    - name: Upload template as artifact
      uses: actions/upload-artifact@v4
      with:
        name: helm-template
        path: "${{ github.event.repository.name }}.yaml"

  slackNotification-helmTemplate:
    name: Slack Notification
    needs: helm-template
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "Helm template created successfully"


  pull-argocd:
    needs: helm-template
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v6
      with:
       repository: kfirbros123/argo-gitops
       ref: application
       path: application

    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: helm-template  
        path: application/app1/dev/

    - name: list files
      run: ls -Ra application/

    - name: commit and push
      run: |
          cd application
          git config user.name "kfirbros123"
          git config user.email "bobytb143@gmail.com"
          git add .
          git commit -m "generated"
          git push https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/kfirbros123/argo-gitops.git HEAD:application



 